### PR TITLE
Friends list

### PR DESCRIPTION
**Pull request by ajbyrd**
# Description

Functionality for adding friends by name is now part of the app.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing Instructions

Please describe the tests required to verify your changes. Provide instructions so PR Tester can check functionality. Please also list any relevant details for your tests

git fetch --all
git checkout friends-list
run webpack
check and see if you can use the add friend button and add a friend by name to the database.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by sophiahoffman — APPROVED** [review]
it's alive!!! weird science

**Review by RyanCrowleyCode — APPROVED** [review]
Button is on the dom, pulls up form for adding friend

**Comment by JohnALong** [comment]
tested button - friend added to database

**Review by JohnALong — APPROVED** [review]
works great

**Pull request merged**
